run:
    python train_network2.py

run-args:
    python train_network2.py --epochs 1000 --batch-size 32 --lr 0.001

# install:
#     pip install -r requirements.txt

# clean:
#     rm -rf __pycache__ *.pyc experiments/max_cut/neural_network/saved_models/*